version: '1'
services:
  odoo:
    build: .
    image: odoo-fe:12
    container_name: cont_odoo_fe_12-proy1
    depends_on:
      - db
    volumes:
      - "./src:/opt/odoo"
      - "data-odoo-12:/filestore"
    environment:
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_ADMIN_PASSWORD=randompass
      - ODOO_DB_HOST=db
    ports:
      - "8069:8069"
      - "8072:8069"
    restart: always
    command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc"
    #command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc -d odoodb -i base"
    #command: "tail -f /dev/null"
    networks: 
      - red-odoo12-db
  db:
    image: postgres:9.6
    container_name: cont_db_fe_12-proy1
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres      
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db-12:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: always
    networks: 
      - red-odoo12-db
      
networks:
   red-odoo12-db:
  
volumes:
  data-odoo-12:
  data-db-12:
